
spring:
# MySQL connection properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
# Point to Vault secure dbusername    
    username: ${dbusername}
# Point to Vault secure dbpassword 
    password: ${dbpassword}
    url: jdbc:mysql://localhost:3306/healthcaredb?createDatabaseIfNotExist=true&useSSL=false

welcome:
  message: DEV Env- Welocome to user module 
secret:
  key: agdidj6ytre3dvcghkl2fdshskds0jdjd53sjdfsrsim
